#!/bin/sh

cat <<! > edge-vpn/DEBIAN/control
Package: edge-vpn
Name: EdgeVPN
Version: 20.7.2
Maintainer: <edge@edge-vpn.org>
Architecture: $(dpkg --print-architecture)
Homepage: http://edge-vpn.org
Depends: python3, python3-dev, python3-pip, iproute2, openvswitch-switch, bridge-utils
Description: Virtual Overlay Networks.
 EdgeVPN is an open-source user-centric software virtual network allowing end users to define and create their own virtual private networks (VPNs). IPOP virtual networks provide end-to-end tunneling of IP or Ethernet over Tincan links setup and managed through a control API to create various software-defined VPN overlays.
Tag: P2P Overlay Networking
!

dpkg-deb --build --root-owner-group edge-vpn .

rm edge-vpn/DEBIAN/control
