#!/bin/sh

cat <<! > edgevpnio/DEBIAN/control
Package: edgevpnio
Name: EdgeVPN.io
Version: 20.7.2
Maintainer: <contact@edgevpn.io>
Architecture: $(dpkg --print-architecture)
Homepage: http://edgevpn.io
Depends: python3, python3-dev, python3-pip, iproute2, openvswitch-switch, bridge-utils
Description: Virtual Overlay Networks.
 EdgeVPN.io is an open-source software for deploying scalable VPNs across distributed edge resources
Tag: P2P Overlay Virtual Networking
!

dpkg-deb --build --root-owner-group edgevpnio .

rm edgevpnio/DEBIAN/control
