#!/bin/bash

function prereqs
{
  sudo bash -c "
    apt-get update -y && \
    apt-get install -y openvswitch-switch=2.9.2-0ubuntu0.18.04.3 \
                        python3.6 python3-pip python3-venv \
                        apt-transport-https \
                        ca-certificates \
                        curl git \
                        software-properties-common && \

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable\" && \
    apt-cache policy docker-ce && \
    apt-get install -y containerd.io=1.2.6-3 \
                       docker-ce-cli=5:18.09.7~3-0~ubuntu-bionic \
                       docker-ce=5:18.09.7~3-0~ubuntu-bionic && \
    groupadd -f docker && \
    echo $user_name && \
    usermod -a -G docker $USER \
  "
}

function venv
{
  python3 -m venv exp-venv
  source exp-venv/bin/activate
  pip3 install simplejson==3.16.0
}

function img
{
  # docker build -f docker/edgev-base.Dockerfile -t kcratie/edgev-base:1.0 ./docker
  docker build -f docker/edgev.Dockerfile -t kcratie/edge-vpn:20.7 ./docker
}

case $1 in
  prereqs)
    prereqs
    ;;
  venv)
    venv
    ;;
  img)
    img
    ;;
  *)
    echo "no match on input -> $1"
    ;;
esac
