#!/bin/bash

function prereqs
{
  sudo bash -c "
    apt-get update -y && \
    apt-get install -y openvswitch-switch \
                        python3.7 python3-pip python3-venv \ python3-dev
                        apt-transport-https \
                        ca-certificates \
                        curl git \
                        software-properties-common && \

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable\" && \
    apt-cache policy docker-ce && \
    apt-get install -y containerd.io \
                       docker-ce-cli \
                       docker-ce && \
    groupadd -f docker && \
    usermod -a -G docker $USER \
  "
}

function venv
{
  python3 -m venv exp-venv
  source exp-venv/bin/activate
  pip3 install simplejson
}

function img
{
  docker build -f docker/edgev-base.Dockerfile -t kcratie/edgev-base:1.0 ./docker
  docker build -f docker/edgev.Dockerfile -t kcratie/edge-vpn:20.7 ./docker
}

case $1 in
  prereqs)
    prereqs
    ;;
  venv)
    venv
    ;;
  img)
    img
    ;;
  *)
    echo "no match on input -> $1"
    ;;
esac
